package Vista;

import Controlador.CRUD_Autores;
import Controlador.CRUD_Galerias;
import Modelo.Autor;
import Modelo.Galerias;
import Modelo.Usuarios;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class frmVisor extends javax.swing.JInternalFrame {

    //variable para determinar desde que boton llamar el user
    public static String mantenedor;
    //Objeto de tipo tabla
    DefaultTableModel tabla = new DefaultTableModel();

    public void Llenar() {
        switch (mantenedor) {
            case "Galerías":
                CRUD_Galerias crudg = new CRUD_Galerias();
                //cargar datos de autores
                ArrayList<Galerias> datosg = crudg.read();
                //Objeto de tipo tabla
                DefaultTableModel tabla = new DefaultTableModel();
                tabla.setColumnCount(0);
                tabla.addColumn("Nombre");
                tabla.addColumn("ubicación");
                //Definir cantidad de filas
                tabla.setNumRows(datosg.size());
                //Crear instancia de clase Autor
                Galerias galeria = new Galerias();
                //Agregar datos a la tabla
                for (int i = 0; i < datosg.size(); i++) {
                    //Casting de datos
                    galeria = (Galerias) datosg.get(i);
                    tabla.setValueAt(galeria.getNombreGaleria(), i, 0);
                    tabla.setValueAt(galeria.getUbicacionGaleria(), i, 1);
                }
                jTable1.setModel(tabla);
                break;
            case "Obras de Arte":
                break;
            case "Autores":
                CRUD_Autores cruda = new CRUD_Autores();
                //cargar datos de autores
                ArrayList<Autor> datosa = cruda.read();
                tabla.setColumnCount(0);
                tabla.addColumn("Código");
                tabla.addColumn("Nombre");
                tabla.addColumn("Fecha Nacimiento");
                tabla.addColumn("Fecha Defunción");
                //Definir cantidad de filas
                tabla.setNumRows(datosa.size());
                //Crear instancia de clase Autor
                Autor autor = new Autor();
                //Agregar datos a la tabla
                for (int i = 0; i < datosa.size(); i++) {
                    //Casting de datos
                    autor = (Autor) datosa.get(i);
                    tabla.setValueAt(autor.getAut_cod(), i, 0);
                    tabla.setValueAt(autor.getAut_nom(), i, 1);
                    tabla.setValueAt(autor.getAut_f_nac(), i, 2);
                    tabla.setValueAt(autor.getAut_f_def(), i, 3);
                }
                jTable1.setModel(tabla);
                break;
        }
    }

    public frmVisor() {
        initComponents();
        this.setTitle(mantenedor);
        Llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jTextField1.setText("jTextField1");
        jToolBar1.add(jTextField1);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
